# Generated by Django 4.2.5 on 2023-09-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_complaint_id_complaint_complaint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_id',
        ),
        migrations.AddField(
            model_name='complaint',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
