# Generated by Django 4.2.5 on 2023-09-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_complaint_complaint_id_complaint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='tit',
            field=models.CharField(default=212, max_length=200),
            preserve_default=False,
        ),
    ]
