# Generated by Django 4.0.4 on 2022-05-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
